#ifndef GAME_INCLUDES_H
#define GAME_INCLUDES_H

#include <common.h>

#include "game/226/R226.c"
#include "game/227/R227.c"
#include "game/228/R228.c"
#include "game/229/R229.c"
#include "game/226/226_00_DrawLevelOvr1P.c"
#include "game/227/227_00_DrawLevelOvr2P.c"
#include "game/228/228_00_DrawLevelOvr3P.c"
#include "game/229/229_00_DrawLevelOvr4P.c"
#include "game/DrawConfetti/DrawConfetti.c"
#include "game/DrawSky/DrawSky.c"

#include "game/RenderBucket/RenderBucket_08_InitDepthGTE.c"
#include "game/RenderBucket/RenderBucket_QueueExecute.c"
#include "game/RenderLevel/AnimateWater.c"
#include "game/RenderLevel/RenderLists.c"
#include "game/RenderTires/DrawTires_Solid.c"
#include "game/RenderTires/DrawTires_Reflection.c"
#include "game/RenderStars/RenderStars.c"
#include "game/Torch/Torch.c"
#include "game/RenderWeather/RedBeaker_RenderRain.c"
#include "game/RenderWeather/RenderWeather.c"

#include "game/MAIN/MAIN_AAA_BigBlock1.c"

#include "game/CAM.c"

#include "game/BOTS.c"
#include "game/CDSYS.c"

#include "game/COLL.c"

#include "game/CTR/CTR_00_Box_DrawWirePrims.c"
#include "game/CTR/CTR_01_Box_DrawWireBox.c"
#include "game/CTR/CTR_02_Box_DrawClearBox.c"
#include "game/CTR/CTR_03_Box_DrawSolidBox.c"
#include "game/CTR/CTR_04_CycleTex_LEV.c"
#include "game/CTR/CTR_05_CycleTex_Model.c"
#include "game/CTR/CTR_06_CycleTex_AllModels.c"
#include "game/CTR/CTR_07_CycleTex_2p3p4pWumpaHUD.c"
#include "game/CTR/CTR_08_ClearRenderLists_1P2P.c"
#include "game/CTR/CTR_09_ClearRenderLists_3P4P.c"
#include "game/CTR/CTR_10_EmptyFunc_MainFrame_ResetDB.c"
#include "game/CTR/CTR_11_ErrorScreen.c"
#include "game/CTR/CTR_12_unknownMaybeThunk1.c"
#include "game/CTR/CTR_14_unknownMaybeThunk2.c"
#include "game/CTR/CTR_16_unknownMaybeThunk3.c"
#include "game/CTR/CTR_17_MatrixToRot.c"
#include "game/CTR/CTR_18_ScrambleGhostString.c"

#include "game/DebugFont.c"

#include "game/DecalFont.c"

#include "game/DecalGlobal.c"

#include "game/DecalHUD.c"

#include "game/DecalMP.c"

#include "game/Display.c"

#include "game/DotLights.c"

#include "game/DropRain.c"

#include "game/ElimBG.c"

#include "game/FLARE.c"

#include "game/GAMEPAD.c"

#include "game/GAMEPROG.c"

#include "game/GhostReplay.c"

#include "game/GhostTape.c"

#include "game/HOWL/h01_CountSounds.c"
#include "game/HOWL/h02_OtherFX_Play.c"
#include "game/HOWL/h03_OtherFX_Play_Echo.c"
#include "game/HOWL/h04_OtherFX_Play_LowLevel.c"
#include "game/HOWL/h05_OtherFX_Modify.c"
#include "game/HOWL/h06_OtherFX_Stop1.c"
#include "game/HOWL/h07_OtherFX_Stop2.c"
#include "game/HOWL/h119_GTE_AudioLR_Inst.c"
#include "game/HOWL/h120_GTE_AudioLR_Driver.c"
#include "game/HOWL/h121_GTE_GetSquaredLength.c"
#include "game/HOWL/h122_OtherFX_RecycleNew.c"
#include "game/HOWL/h123_OtherFX_RecycleMute.c"
#include "game/HOWL/h124_OtherFX_DriverCrashing.c"
#include "game/HOWL/h125_GTE_GetSquaredDistance.c"
#include "game/HOWL/h126_CalculateVolumeFromDistance.c"
#include "game/HOWL/h127_PlayWarppadSound.c"
#include "game/HOWL/h128_Level_SoundLoopSet.c"
#include "game/HOWL/h129_Level_SoundLoopFade.c"
#include "game/HOWL/h130_Level_RandomFX.c"
#include "game/HOWL/h131_Level_AmbientSound.c"
#include "game/HOWL/h132_PlaySound3D.c"
#include "game/HOWL/h133_PlaySound3D_Flags.c"
#include "game/HOWL/h08_EngineAudio_InitOnce.c"
#include "game/HOWL/h09_EngineAudio_Recalculate.c"
#include "game/HOWL/h134_EngineSound_Player.c"
#include "game/HOWL/h135_EngineSound_VolumeAdjust.c"
#include "game/HOWL/h136_EngineSound_AI.c"
#include "game/HOWL/h137_EngineSound_NearestAIs.c"
#include "game/HOWL/h10_EngineAudio_Stop.c"
#include "game/HOWL/h11_SetReverbMode.c"
#include "game/HOWL/h12_CseqMusic_Start.c"
#include "game/HOWL/h13_CseqMusic_Pause.c"
#include "game/HOWL/h14_CseqMusic_Resume.c"
#include "game/HOWL/h15_CseqMusic_ChangeVolume.c"
#include "game/HOWL/h16_CseqMusic_Restart.c"
#include "game/HOWL/h17_CseqMusic_ChangeTempo.c"
#include "game/HOWL/h18_CseqMusic_AdvHubSwap.c"
#include "game/HOWL/h19_CseqMusic_Stop.c"
#include "game/HOWL/h20_CseqMusic_StopAll.c"
#include "game/HOWL/h21_Bank_ResetAllocator.c"
#include "game/HOWL/h22_Bank_Alloc.c"
#include "game/HOWL/h23_Bank_AssignSpuAddrs.c"
#include "game/HOWL/h24_Bank_Destroy.c"
#include "game/HOWL/h25_Bank_ClearInRange.c"
#include "game/HOWL/h26_Bank_Load.c"
#include "game/HOWL/h27_Bank_DestroyLast.c"
#include "game/HOWL/h28_Bank_DestroyUntilIndex.c"
#include "game/HOWL/h29_Bank_DestroyAll.c"
#include "game/HOWL/h30_howl_InstrumentPitch.c"
#include "game/HOWL/h31_howl_InitGlobals.c"
#include "game/HOWL/h32_howl_ParseHeader.c"
#include "game/HOWL/h33_howl_ParseCseqHeader.c"
#include "game/HOWL/h34_howl_LoadHeader.c"
#include "game/HOWL/h35_howl_SetSong.c"
#include "game/HOWL/h36_howl_LoadSong.c"
#include "game/HOWL/h37_howl_ErasePtrCseqHeader.c"
#include "game/HOWL/h38_howl_GetNextNote.c"
#include "game/HOWL/h39_cseq_opcode01_noteoff.c"
#include "game/HOWL/h40_cseq_opcode03.c"
#include "game/HOWL/h41_howl_InitChannelAttr_Music.c"
#include "game/HOWL/h42_cseq_opcode_from06and07.c"
#include "game/HOWL/h43_cseq_opcode05_noteon.c"
#include "game/HOWL/h44_cseq_opcode06.c"
#include "game/HOWL/h45_cseq_opcode07.c"
#include "game/HOWL/h46_cseq_opcode08.c"
#include "game/HOWL/h47_cseq_opcode09.c"
#include "game/HOWL/h48_cseq_opcode0a.c"
#include "game/HOWL/h49_SongPool_FindFreeChannel.c"
#include "game/HOWL/h50_SongPool_CalculateTempo.c"
#include "game/HOWL/h51_SongPool_ChangeTempo.c"
#include "game/HOWL/h52_SongPool_Start.c"
#include "game/HOWL/h53_SongPool_Volume.c"
#include "game/HOWL/h54_SongPool_AdvHub1.c"
#include "game/HOWL/h55_SongPool_AdvHub2.c"
#include "game/HOWL/h56_SongPool_StopCseq.c"
#include "game/HOWL/h57_SongPool_StopAllCseq.c"
#include "game/HOWL/h58_howl_Disable.c"
#include "game/HOWL/h59_UpdateChannelVol_EngineFX.c"
#include "game/HOWL/h60_UpdateChannelVol_OtherFX.c"
#include "game/HOWL/h61_UpdateChannelVol_Music.c"
#include "game/HOWL/h62_UpdateChannelVol_EngineFX_All.c"
#include "game/HOWL/h63_UpdateChannelVol_Music_All.c"
#include "game/HOWL/h64_UpdateChannelVol_OtherFX_All.c"
#include "game/HOWL/h65_howl_VolumeGet.c"
#include "game/HOWL/h66_howl_VolumeSet.c"
#include "game/HOWL/h67_howl_ModeGet.c"
#include "game/HOWL/h68_howl_ModeSet.c"
#include "game/HOWL/h69_OptionsMenu_TestSound.c"
#include "game/HOWL/h70_Smart_EnterCriticalSection.c"
#include "game/HOWL/h71_Smart_ExitCriticalSection.c"
#include "game/HOWL/h72_Channel_SetVolume.c"
#include "game/HOWL/h73_Channel_FindSound.c"
#include "game/HOWL/h74_Channel_AllocSlot_AntiSpam.c"
#include "game/HOWL/h75_Channel_AllocSlot.c"
#include "game/HOWL/h76_Channel_SearchFX_EditAttr.c"
#include "game/HOWL/h77_Channel_SearchFX_Destroy.c"
#include "game/HOWL/h78_Channel_DestroyAll_LowLevel.c"
#include "game/HOWL/h79_Channel_ParseSongToChannels.c"
#include "game/HOWL/h80_Channel_UpdateChannels.c"
#include "game/HOWL/h81_Cutscene_VolumeBackup.c"
#include "game/HOWL/h82_Cutscene_VolumeRestore.c"
#include "game/HOWL/h83_howl_PlayAudio_Update.c"
#include "game/HOWL/h84_howl_InitChannelAttr_EngineFX.c"
#include "game/HOWL/h85_howl_InitChannelAttr_OtherFX.c"
#include "game/HOWL/h86_howl_PauseAudio.c"
#include "game/HOWL/h87_howl_UnPauseChannel.c"
#include "game/HOWL/h88_howl_UnPauseAudio.c"
#include "game/HOWL/h89_howl_StopAudio.c"
#include "game/HOWL/h90_Voiceline_PoolInit.c"
#include "game/HOWL/h91_Voiceline_ClearTimeStamp.c"
#include "game/HOWL/h92_Voiceline_PoolClear.c"
#include "game/HOWL/h93_Voiceline_StopAll.c"
#include "game/HOWL/h94_Voiceline_ToggleEnable.c"
#include "game/HOWL/h95_Voiceline_RequestPlay.c"
#include "game/HOWL/h96_Voiceline_StartPlay.c"
#include "game/HOWL/h97_Voiceline_Update.c"
#include "game/HOWL/h98_Voiceline_EmptyFunc.c"
#include "game/HOWL/h99_Voiceline_SetDefaults.c"
#include "game/HOWL/h100_Audio_SetState.c"
#include "game/HOWL/h101_Audio_SetState_Safe.c"
#include "game/HOWL/h102_Audio_AdvHub_SwapSong.c"
#include "game/HOWL/h103_Audio_SetMaskSong.c"
#include "game/HOWL/h104_Audio_Update1.c"
#include "game/HOWL/h105_Audio_SetDefaults.c"
#include "game/HOWL/h106_Audio_SetReverbMode.c"
#include "game/HOWL/h107_Music_SetIntro.c"
#include "game/HOWL/h108_Music_LoadBanks.c"
#include "game/HOWL/h109_Music_AsyncParseBanks.c"
#include "game/HOWL/h110_Music_SetDefaults.c"
#include "game/HOWL/h111_Music_Adjust.c"
#include "game/HOWL/h112_Music_LowerVolume.c"
#include "game/HOWL/h113_Music_RaiseVolume.c"
#include "game/HOWL/h114_Music_Restart.c"
#include "game/HOWL/h115_Music_Stop.c"
#include "game/HOWL/h116_Music_Start.c"
#include "game/HOWL/h117_Music_End.c"
#include "game/HOWL/h118_Music_GetHighestSongPlayIndex.c"
#include "game/HOWL/h138_Garage_Init.c"
#include "game/HOWL/h139_Garage_Enter.c"
#include "game/HOWL/h140_Garage_PlayFX.c"
#include "game/HOWL/h141_Garage_LerpFX.c"
#include "game/HOWL/h142_Garage_MoveLR.c"
#include "game/HOWL/h143_Garage_Leave.c"

#include "game/INSTANCE.c"

#include "game/LHMatrix.c"

#include "game/JitPool.c"

#include "game/LevInstDef.c"

#include "game/LibraryOfModels/LibraryOfModels_1_Clear.c"

#include "game/LinkedCollide.c"

#include "game/LIST.c"

#include "game/LOAD/LOAD_00_50_FULL.c"

#include "game/MAIN/MainDB_00_GetClipSize.c"
#include "game/MAIN/MainDB_01_PrimMem.c"
#include "game/MAIN/MainDB_02_OTMem.c"
#include "game/MAIN/MainDrawCb_00_DrawSync.c"
#include "game/MAIN/MainDrawCb_01_Vsync.c"

#include "game/MAIN/MainFrame_00_TogglePauseAudio.c"
#include "game/MAIN/MainFrame_01_ResetDB.c"
#include "game/MAIN/MainFrame_02_GameLogic.c"
#include "game/MAIN/MainFrame_05_InitVideoSTR.c"
#include "game/MAIN/MainFrame_06_HaveAllPads.c"
#include "game/MAIN/MainFrame_07_VisMemFullFrame.c"
#include "game/MAIN/MainFrame_07_RequestMaskHint.c"
#include "game/MAIN/MainFrame_08_RenderFrame.c"

#include "game/MAIN/MainFreeze.c"

#include "game/MAIN/MainGameStart_00_Initialize.c"
#include "game/MAIN/MainGameEnd_00_SoloRaceGetReward.c"
#include "game/MAIN/MainGameEnd_01_SoloRaceSaveHighScore.c"
#include "game/MAIN/MainGameEnd_02_Initialize.c"
#include "game/MAIN/MainStats_00_ClearBattleVS.c"
#include "game/MAIN/MainStats_01_RestartRaceCountLoss.c"

#include "game/MAIN/MainRaceTrack_00_StartLoad.c"
#include "game/MAIN/MainRaceTrack_01_RequestLoad.c"

#include "game/MATH/MATH_1_Cos.c"
#include "game/MATH/TRIG_AngleSinCos.c"
#include "game/MATH/MATH_2_FastSqrt.c"
#include "game/MATH/MATH_3_HitboxMatrix.c"
#include "game/MATH/MATH_7_MatrixStubs.c"
#include "game/MATH/MATH_MatrixRotate.c"
#include "game/MATH/MATH_6_MatrixMul.c"

#include "game/MEMCARD/MEMCARD_00_SetIcon.c"
#include "game/MEMCARD/MEMCARD_01_CRC16.c"
// NOTE(aalhendi): CTR_NATIVE routes host-backed card operations through MEMCARD_NativeAdapter; non-native builds use the retail card functions below.
#if defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_NativeAdapter.c"
#else
#include "game/MEMCARD/MEMCARD_16_GetFreeBytes.c"
#include "game/MEMCARD/MEMCARD_18_GetInfo.c"
#include "game/MEMCARD/MEMCARD_21_Format.c"
#include "game/MEMCARD/MEMCARD_22_IsFile.c"
#include "game/MEMCARD/MEMCARD_23_FindFirstGhost.c"
#include "game/MEMCARD/MEMCARD_24_FindNextGhost.c"
#include "game/MEMCARD/MEMCARD_25_EraseFile.c"
#endif
#include "game/MEMCARD/MEMCARD_02_ChecksumSave.c"
#include "game/MEMCARD/MEMCARD_03_ChecksumLoad.c"
#include "game/MEMCARD/MEMCARD_04_StringInit.c"
#include "game/MEMCARD/MEMCARD_05_StringSet.c"
#include "game/MEMCARD/MEMCARD_06_InitCard.c"
#include "game/MEMCARD/MEMCARD_07_CloseCard.c"
#include "game/MEMCARD/MEMCARD_08_GetNextSwEvent.c"
#include "game/MEMCARD/MEMCARD_09_GetNextHwEvent.c"
#include "game/MEMCARD/MEMCARD_10_WaitForHwEvent.c"
#include "game/MEMCARD/MEMCARD_11_SkipEvents.c"
#include "game/MEMCARD/MEMCARD_12_NewTask.c"
#include "game/MEMCARD/MEMCARD_13_CloseFile.c"
#include "game/MEMCARD/MEMCARD_14_ReadFile.c"
#include "game/MEMCARD/MEMCARD_15_WriteFile.c"
#if !defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_17_HandleEvent.c"
#endif
#if !defined(CTR_NATIVE)
#include "game/MEMCARD/MEMCARD_19_Load.c"
#include "game/MEMCARD/MEMCARD_20_Save.c"
#endif

#include "game/MEMPACK.c"

#include "game/MixRNG/PSX_BIOS_Rand.c"
#include "game/MixRNG/RngDeadCoed.c"
#include "game/MixRNG/MixRNG_0_Scramble.c"
#include "game/MixRNG/MixRNG_1_Particles.c"
#include "game/MixRNG/MixRNG_2_GetValue.c"

#include "game/Particle.c"

#include "game/PickupBots/PickupBots_0_Init.c"
#include "game/PickupBots/PickupBots_1_Update.c"

#include "game/PROC.c"

#include "game/PushBuffer.c"

#include "game/QueueLoadTrack.c"

#include "game/Podium/Podium_0_InitModels.c"

#include "game/RaceFlag.c"

#include "game/RECTMENU.c"

#include "game/RaceConfig.c"

#include "game/RefreshCard.c"

#include "game/SelectProfile.c"

#include "game/TakeCupProgress.c"

#include "game/SubmitName/SubmitName_0_RestoreName.c"
#include "game/SubmitName/SubmitName_1_DrawMenu.c"
#include "game/SubmitName/SubmitName_2_MenuProc.c"

#include "game/Timer/Timer_0_Init.c"
#include "game/Timer/Timer_1_Destroy.c"
#include "game/Timer/Timer_2_GetTime_Total.c"
#include "game/Timer/Timer_3_GetTime_Elapsed.c"

#include "game/prim.c"
#include "game/math.c"
#include "game/gte.c"
#include "game/MATH/MATH_4_VectorLength.c"
#include "game/MATH/MATH_5_VectorNormalize.c"
#include "game/UI/UI_Reward.c"
#include "game/UI/UI_Convert.c"
#include "game/UI/UI_Instance.c"
#include "game/UI/UI_Map.c"
#include "game/UI/UI_Icon.c"
#include "game/UI/UI_Lerp2D.c"
#include "game/UI/UI_Clock.c"
#include "game/UI/UI_RaceHud.c"
#include "game/UI/UI_Weapon.c"
#include "game/UI/UI_DrawNum.c"
#include "game/UI/UI_Speedometer.c"
#include "game/UI/UI_Meter.c"
#include "game/UI/UI_Rank.c"
#include "game/UI/UI_RenderFrame.c"
#include "game/UI/UI_VsQuip.c"
#include "game/UI/UI_RaceFlow.c"
#include "game/UI/UI_CupStandings.c"

#include "game/Vehicle/VehBirth.c"
#include "game/Vehicle/VehCalc.c"
#include "game/Vehicle/VehAfterColl.c"
#include "game/Vehicle/VehEmitter.c"
#include "game/Vehicle/VehFire.c"
#include "game/Vehicle/VehFrame.c"
#include "game/Vehicle/VehLap.c"
#include "game/Vehicle/VehPhysCrash.c"

#include "game/Vehicle/VehPhysForce.c"
#include "game/Vehicle/VehGroundShadow.c"
#include "game/Vehicle/VehPhysGeneral.c"
#include "game/Vehicle/VehPhysJoystick.c"
#include "game/Vehicle/VehGroundSkids.c"

#include "game/Vehicle/VehPhysProc.c"

#include "game/Vehicle/VehPickupItem.c"
#include "game/Vehicle/VehPickState.c"

#include "game/Vehicle/VehStuckProc.c"

#include "game/Vehicle/VehTurbo.c"
#include "game/Vehicle/VehTalkMask.c"

#include "game/Vector.c"

#include "game/221.c"
#include "game/222.c"
#include "game/223.c"
#include "game/224.c"
#include "game/225.c"

#include "game/221_225_EndEvent.c"

#include "game/PlayLevel/PlayLevel_0_UpdateLapStats.c"

#include "game/230/R230.c"
#include "game/230/D230.c"
#include "game/230/230_Full.c"

#include "game/231/R231.c"
#include "game/231/D231.c"
#include "game/231/231_Full.c"

#include "game/232/R232.c"
#include "game/232/D232.c"

#include "game/232/232_Full.c"

#include "game/233/233_Full.c"

#endif
